### PR TITLE
Import base images from library

### PR DESCRIPTION
**Pull request by josecelano**
I'm working on issue #1 

I'm creating a new workflow to import Base images from the library repo: https://github.com/Nautilus-Cyberneering/chinese-ideographs

For the time being, it's going to be a scheduled workflow (executed every hour) that will pull and auto-commit new Base images into this repo.

### CODE REVIEW

**Comment by josecelano** [comment]
The auto-commit for new images is done. As you can see below TIF images have been added with two signed commit:
image
There are at least two pending tasks to finish this issue:

1. Set `changes_detected` output variable value
2. Update images. The `repo.create_file(base_image_path, commit_message, content, branch)` only works for new files. We have to use a different function ([update_file](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.update_file)) to update files. You have to add the `sha` argument when you want to update files that already exist in the repo/branch.
3. Delete images. We should remove images from the repo when the Base image has been deleted from the library repo.

**Comment by josecelano** [comment]
Update:

1.- `changes_detected` output var working perfectly. The website is re-built if image changes are detected.
2.- Update image is not working. It seems the tif image is not stored correctly. It's working on this test repo: https://github.com/josecelano/pygithub
3.- Cascade delete not implemented. Delete image when Base image is deleted on the source library.

Regarding point 2, images in the library and the repo do not even have the same size. Artifac with images can be downloaded from https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/actions/runs/1409207265 and images have the right size (same as the library). So the problem must be in the GitHub API request. Maybe base64 encode, the file is being truncated, ...

**Comment by josecelano** [comment]
I have fixed point 2 (update image with commit). The problem was we do not need to encode in base64 the image. The Python package already does it internally.

**Comment by josecelano** [comment]
I'm testing the three possible changes when you sync library (submodule with Base images) with the website:

1. Add new Base image
2. Modify Base image
3. Delete Base image

Regarding modifying an image there are a couple of surprising points:

1. Dvc diff gives higher priority to "add" change.

I have two sequential commits:

```
* e016199 - (HEAD -> main, origin/main) Modify Gold and Base images for artwork 000003 (2021-11-02 16:47:13 +0000) <Jose Celano>
* e336f28 - Add Gold and Base image: 000003-32.600.2.tif, 000003-42.600.2.tif (2021-11-02 13:01:42 +0000) <Jose Celano>
*   318039d - Merge pull request #99 from Nautilus-Cyberneering/issue-74-rename-act-secrets-file (2021-10-29 10:40:02 +0100) <yeraydavidrodriguez>
``
The first one adds two images and the second one modifies the same images. 

If you compare the last commit (modify) with the previous (add) you get (`dvc diff --show-json e336f28 e016199`):
```
{
  "added": [],
  "deleted": [],
  "modified": [
    {
      "path": "data/000003/32/000003-32.600.2.tif"
    },
    {
      "path": "data/000003/42/000003-42.600.2.tif"
    }
  ],
  "renamed": []
}
```
Images were modified in the last commit.

But if you compare the last commit (modify) with a commit before adding the images you get (`dvc diff --show-json 318039d e016199`):
```
{
  "added": [
    {
      "path": "data/000003/32/000003-32.600.2.tif"
    },
    {
      "path": "data/000003/42/000003-42.600.2.tif"
    }
  ],
  "deleted": [],
  "modified": [],
  "renamed": []
}
```
Images are included in `added` array. Images were added and later modified, but dvc diff includes them only in added.

You can see the workflow log here: https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/runs/4082976055?check_suite_focus=true#step:6:8

2. Error: Image already added tho the PR branch

I'm getting an error trying to commit the modified image: https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/runs/4082976055?check_suite_focus=true#step:11:208

When we run the workflow we checkout the commit that triggered the event. As you can see see in the workflow log:

```
Current Base images in website ...
./public/images/000001-42.600.2.tif
./public/images/000002-42.600.2.tif
```

The commit did not have at that time the modified image. Since we update the library (submodule) we get the newer images:

```
Find Base images in library ...
./library/data/000002/42/000002-42.600.2.tif
./library/data/000003/42/000003-42.600.2.tif
./library/data/000001/42/000001-42.600.2.tif
```

We have the modified image `./library/data/000003/42/000003-42.600.2.tif`. We detect it as an untracked image and we try to create the file in the PR branch. We get this error because the image already exists in the branch:

```
github.GithubException.GithubException: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
```

Although the image does not exist in the PR commit it exists in the branch because it was committed in a previous workflow execution. We have two options to fix this problem:

**Solution 1**

We can create a new commit using `repo.update_file` instead of `repo.create_file`. First, we have to find out whether the files already exists or not. This solution generates a new commit for all image changes every time the workflow is executed which is a bad idea.

**Solution 2**

We could check if the image already exists in the branch and if it's the same version (sha). If the image exists and it has the same hash we don't create the commit. The workflow should be deterministic. It should produce the same output even if you execute it more than once. If we have added one Base image in the library we should have only one commit in the website adding the image. If there have been more than 1 operation, for example, adding and modifying the Base image, we should have only the final effect in the website, that's is add the final version of the image.

For example:

Library:
1. Time-1: Add image 1.0
2. Time-3: Modify image 1.1
3. Time-4: Modify image 1.2
4. Time-5: Modify image 1.3
5. Time-9: Delete image 1.3

Website:
1. Time-2: Add image 1.0
2. Time-6: Update image 1.3
3. Time-7: No new commit created for image 1.3
4. Time-8: No new commit created for image 1.3
5. Time-10: Delete image 1.3

In that example, we add and modify the library and we only sync the website at Time-1 and Time-6. When the website workflow is executed at Time-6 we `dvc pull` the latest version of the image and we create only one commit with version 1.3

**Comment by josecelano** [comment]
I've implemented solution 2. I do not know yet if it works because I was testing with a [larger image](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/data/000003/42/000003-42.600.2.tif.dvc) (70MB) and it seems the API can't accept that file size. The workflow is failing with "Server Error" after submitting the request to the GItHub API: https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/actions/runs/1417659849

I'm going to change the image to use a smaller one in order to test the new feature (solution 2). After checking that solution I will continue with this new problem, the image size. Anyway after finding a new way to sign commits without using the GitHub API I would prefer to use that one because:

1. We avoid distributed changes: changes locally in the local workflow git repo and remotely using the branch. That leads to problems having 2 versions of the branch. Anyway, we still need to check if the new way of adding signed commit is valid in our case. I have been using this repo https://github.com/josecelano/pygithub for tests.
2. We avoid network problems. We can make local git changes and I think even "git push" commands are going to be more reliable using the local git rather than the API.

**Comment by josecelano** [comment]
With this git configuration the commit is not signed:

```
      - name: Commit submodule udpate
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # Remove untracked images (commited with GitHub API)
          git clean -f
          # Sync branch. Pull new images commited with GitHub API
          git pull
          # Commit submodule (library) update
          git add library && git commit -m "Auto update library submodule:  ${{ steps.update-library.outputs.current_ref }}" && git push || echo "No changes to commit"
```

image

**Comment by josecelano** [comment]
There is still one thing pending to finish. The auto-commit for the submodule update is not signed:

image

but we could merge this issue and create new one for that tasks.

**Review by yeraydavidrodriguez — APPROVED** [review]

**Pull request merged**
